[package]
authors = ["Vladimir Serbinenko <phcoder@gmail.com>"]
edition = "2024"
readme = "README.md"
name = "grub-rust-hello"
version = "0.1.0"

[dependencies]
grub = { workspace = true }

[lib]
crate-type = ["lib", "cdylib"]
